openapi: 3.2.0
info:
  title: Channable order connection Stock Updates API
  description: '# Introduction


    Welcome to the Channable API __v1__.'
  version: v1
  x-logo:
    url: https://www.channable.com/_next/image?url=https%3A%2F%2Fmedia.graphassets.com%2FcntRnbAcSrCmS1wLTWrb&w=256&q=75
tags:
- name: Stock Updates
paths:
  /v1/companies/{company_id}/projects/{project_id}/offers:
    get:
      tags:
      - Stock Updates
      summary: Get Stock Updates
      description: 'This endpoint retrieves all offers for a given project of your company, sorted from most recent

        to oldest. Offers are the product updates that you posted.


        These are found under "Orders" > "Product updates" in the Channable tool.

        Optionally, you can pass query parameters to customize the query and response content.


        **Example usage**


        Suppose the following scenario for a given project of yours:

        - The project contains the offers `o1`, `o2`, `o3`, and `o4` (from oldest to most recent)

        - `o1` and `o4` are searchable by the term `t`

        - `o3` is searchable by the term `tE`


        | Request parameters | Response

        | ------------- | -----------

        | _none_ | `{"offers": [o4, o3, o2, o1], "total": 4}`

        | `?limit=2` | `{"offers": [o4, o3], "total": 2}`

        | `?offset=4` | `{"offers": [], "total": 0}`

        | `?offset=1` | `{"offers": [o3, o2, o1], "total": 3}`

        | `?offset=1&limit=1` | `{"offers": [o3], "total": 1}`

        | `?offset=1&limit=2` | `{"offers": [o3, o2], "total": 2}`

        | `?search=t` | `{"offers": [o4, o1], "total": 2}`

        | `?search=tE` | `{"offers": [o3], "total": 1}`

        | `?start_date=2018-01-01` | `{"offers": [o4, o3, o2], "total": 3}`

        | `?start_date=2018-01-01&end_date=2018-02-28` | `{"offers": [o3, o2], "total": 2}`

        | `?last_modified_after=2018-02-29` | `{"offers": [o4], "total": 1}`'
      operationId: get_stock_updates_companies__company_id__projects__project_id__offers_get
      parameters:
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
          title: Company Id
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
          title: Project Id
      - name: search
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            minLength: 1
          - type: 'null'
          description: Any text based search query
          title: Search
        description: Any text based search query
      - name: start_date
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: Start Date
      - name: end_date
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: End Date
      - name: last_modified_after
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: Last Modified After
      - name: last_modified_before
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: Last Modified Before
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          description: Max number of results in a single page.
          default: 100
          title: Limit
        description: Max number of results in a single page.
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
          description: Filter results starting from this offset.
          default: 0
          title: Offset
        description: Filter results starting from this offset.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecentOffers'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - Stock Updates
      summary: Stock Updates Update (Deprecated)
      description: Use /stock_updates instead
      operationId: Stock_Updates_Update__deprecated__companies__company_id__projects__project_id__offers_post
      deprecated: true
      parameters:
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
          title: Company Id
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
          title: Project Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannableStockUpdatePayload'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockUpdateResponse'
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Accepted
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Unauthorized
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/companies/{company_id}/projects/{project_id}/stock_updates:
    post:
      tags:
      - Stock Updates
      summary: Stock Updates Update
      description: 'This endpoint allows you to update the offers'' stock of a selected project.

        We will then propagate the update to all the marketplaces of the targeted project.'
      operationId: stock_updates_update_companies__company_id__projects__project_id__stock_updates_post
      parameters:
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
          title: Company Id
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
          title: Project Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannableStockUpdatePayload'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockUpdateResponse'
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Accepted
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Unauthorized
        '413':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Content Too Large
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    StockUpdateResponse:
      properties:
        status:
          $ref: '#/components/schemas/ResponseModelStatus'
          title: Response Status
        message:
          type: string
          title: Message
        content:
          items:
            $ref: '#/components/schemas/ResponseModel'
          type: array
          title: Upstream Responses
      type: object
      required:
      - status
      - message
      - content
      title: StockUpdateResponse
    RecentOffers:
      properties:
        total:
          type: integer
          title: Total
        offers:
          items:
            $ref: '#/components/schemas/EfferentOffer'
          type: array
          title: Offers
      type: object
      required:
      - total
      - offers
      title: RecentOffers
      example:
        offers:
        - client_id: '2026523'
          created: '2022-04-19T07:18:44.436934+00:00'
          gtin: '1234567890123'
          id: 2251
          modified: '2022-04-19T07:18:44.436934+00:00'
          price: 10.5
          project_id: -1
          stock: 0
          stock_tracking: true
          title: test title
        total: 1
    EfferentOffer:
      properties:
        id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Id
        project_id:
          type: integer
          title: Project Id
        client_id:
          type: string
          title: Client Id
        gtin:
          anyOf:
          - type: string
          - type: 'null'
          title: Gtin
        stock:
          anyOf:
          - type: integer
          - type: 'null'
          title: Stock
        stock_tracking:
          type: boolean
          title: Stock Tracking
        availability:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Availability
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        price:
          anyOf:
          - type: string
            pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
          - type: 'null'
          title: Price
        created:
          type: string
          format: date-time
          title: Created
        modified:
          type: string
          format: date-time
          title: Modified
      type: object
      required:
      - project_id
      - client_id
      - stock_tracking
      - created
      - modified
      title: EfferentOffer
    ChannableApiStockUpdate:
      properties:
        id:
          type: string
          title: Id
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        stock:
          type: integer
          title: Stock
          description: Whole new stock value for the item, not a delta
        gtin:
          anyOf:
          - type: string
          - type: 'null'
          title: Gtin
      type: object
      required:
      - id
      - stock
      title: ChannableApiStockUpdate
      description: 'Channable API payload for sending a stock update for a product.


        Only id and stock are mandatory, as this is all we strictly need to send the update. The rest

        is just for display in the frontend.'
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ChannableStockUpdatePayload:
      items:
        $ref: '#/components/schemas/ChannableApiStockUpdate'
      type: array
      maxItems: 50
      title: ChannableStockUpdatePayload
      example:
      - gtin: 123-456
        id: '123'
        stock: 1
        title: Some offer
    ChannableErrorResponse:
      properties:
        status:
          type: string
          const: error
          title: Status
          default: error
        message:
          type: string
          title: Message
          description: A description about the given error
      type: object
      required:
      - message
      title: ChannableErrorResponse
      description: The standard Channable error response
    ResponseModel:
      properties:
        status:
          $ref: '#/components/schemas/ResponseModelStatus'
          title: Response Status
        message:
          type: string
          title: Message
        response:
          type: string
          title: Response
          default: ''
        id:
          anyOf:
          - type: string
          - type: 'null'
          title: Id
        data:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Data
          description: Data relevant to the specific response. This may vary by endpoint
      type: object
      required:
      - status
      - message
      title: ResponseModel
      description: A container for response model.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ResponseModelStatus:
      type: string
      enum:
      - success
      - error
      - warning
      - debug
      title: ResponseModelStatus
