openapi: 3.2.0
info:
  title: Channable order connection Order Attachments API
  description: '# Introduction


    Welcome to the Channable API __v1__.'
  version: v1
  x-logo:
    url: https://www.channable.com/_next/image?url=https%3A%2F%2Fmedia.graphassets.com%2FcntRnbAcSrCmS1wLTWrb&w=256&q=75
tags:
- name: order_attachments
paths:
  /v1/companies/{company_id}/projects/{project_id}/orders/{order_id}/attachments/{order_attachment_id}:
    get:
      tags:
      - order_attachments
      summary: Order attachment download
      description: 'This endpoint responds with the download URL for an order attachment.

        The download URL is valid for 5 minutes.'
      operationId: order_attachment_download_url_companies__company_id__projects__project_id__orders__order_id__attachments__order_attachment_id__get
      parameters:
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
          title: Company Id
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
          title: Project Id
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          description: The order ID as it is known to Channable
          title: Order Id
        description: The order ID as it is known to Channable
      - name: order_attachment_id
        in: path
        required: true
        schema:
          type: integer
          title: Order Attachment Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderAttachmentDownloadURLResponse'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Not Found
        '410':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Gone
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/companies/{company_id}/projects/{project_id}/orders/{order_id}/attachments:
    post:
      tags:
      - order_attachments
      summary: Order attachment upload
      description: 'Order attachments sent to this endpoint will be uploaded to the marketplace and linked to the specified order (items). A 202 status response indicates the file has been processed and will be uploaded asynchronously.


        Currently only accepts PDF invoices.


        Available for:

        - ANWB

        - Allegro

        - Amazon

        - Bol

        - Boulanger

        - But

        - Carrefour

        - Carrefour France

        - Castorama

        - Channable Sandbox

        - Conforama

        - Conrad

        - Debenhams

        - Decathlon

        - Douglas

        - Galeries LaFayette

        - Home24

        - Hornbach

        - Inno

        - Kaufland

        - Kruidvat

        - La Redoute

        - Le BHV Marais

        - Leen Bakker

        - Leroy Merlin

        - Maisons Du Monde

        - Manor

        - Maxeda Brico

        - Maxeda Praxis

        - MediaMarkt

        - Nextail

        - Nocibe

        - Obelink

        - Pc Componentes

        - Shop Apotheke Austria

        - Shop Apotheke Belgium

        - Shop Apotheke Germany

        - Shop Apotheke Italy

        - Showroomprive

        - Sprinter

        - Teract

        - Worten

        - ePrice

        - fonQ

        - vtwonen'
      operationId: order_attachment_upload_companies__company_id__projects__project_id__orders__order_id__attachments_post
      parameters:
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
          title: Company Id
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
          title: Project Id
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          description: The order ID as it is known to Channable
          title: Order Id
        description: The order ID as it is known to Channable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderAttachmentUploadPayload'
      responses:
        '202':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderAttachmentUploadResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Bad Request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Not Found
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Conflict
        '415':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannableErrorResponse'
          description: Unsupported Media Type
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    OrderAttachmentUploadResponse:
      properties:
        status:
          $ref: '#/components/schemas/ResponseModelStatus'
        order_attachment_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Order Attachment Id
          description: Channable ID for the attachment. Is empty on failure
        message:
          anyOf:
          - type: string
          - type: 'null'
          title: Message
      type: object
      required:
      - status
      title: OrderAttachmentUploadResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ChannableErrorResponse:
      properties:
        status:
          type: string
          const: error
          title: Status
          default: error
        message:
          type: string
          title: Message
          description: A description about the given error
      type: object
      required:
      - message
      title: ChannableErrorResponse
      description: The standard Channable error response
    OrderAttachmentUploadPayload:
      properties:
        attachment_type:
          type: string
          title: Attachment Type
          description: Only `INVOICE` is currently accepted
          default: INVOICE
        file:
          type: string
          title: File
          description: A base64 encoded string
        order_item_ids:
          anyOf:
          - items:
              type: integer
            type: array
          - type: 'null'
          title: Order Item Ids
          description: Only used for Bol invoices. Order item ids of the subset of items the invoiceis for. If omitted the invoice will be linked to all items in the order.
      type: object
      required:
      - file
      title: OrderAttachmentUploadPayload
    OrderAttachmentDownloadURLResponse:
      properties:
        url:
          type: string
          title: Url
      type: object
      required:
      - url
      title: OrderAttachmentDownloadURLResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ResponseModelStatus:
      type: string
      enum:
      - success
      - error
      - warning
      - debug
      title: ResponseModelStatus
