openapi: 3.2.0
info:
  title: Channable order connection Statistics API
  description: '# Introduction


    Welcome to the Channable API __v1__.'
  version: v1
  x-logo:
    url: https://www.channable.com/_next/image?url=https%3A%2F%2Fmedia.graphassets.com%2FcntRnbAcSrCmS1wLTWrb&w=256&q=75
tags:
- name: Statistics
paths:
  /v1/companies/{company_id}/projects/{project_id}/statistics/orders:
    get:
      tags:
      - Statistics
      summary: All Statistics
      description: 'Statistics for all order configs of a project for a given time frame.


        Contains the following information per orders config in the project:

        - Total number of orders

        - Total number of ordered products

        - Total amount spent on commission to marketplaces

        - Total amount spent on shipping costs

        - Total order revenue

        - The currency of the marketplace

        - Daily revenue numbers


        Contains the following information aggregated across all orders configs in the project:

        - Total number of orders

        - Total number of ordered products

        - Total amount spent on commission to marketplaces

        - Total amount spent on shipping costs

        - Total order revenue'
      operationId: all_statistics_companies__company_id__projects__project_id__statistics_orders_get
      parameters:
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
          title: Project Id
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
          title: Company Id
      - name: download
        in: query
        required: false
        schema:
          type: boolean
          description: If true, a file download will be served
          default: false
          title: Download
        description: If true, a file download will be served
      - name: start_date
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: Start Date
      - name: end_date
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: End Date
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatisticsCombined'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/companies/{company_id}/projects/{project_id}/statistics/orders/{order_config_id}:
    get:
      tags:
      - Statistics
      summary: Single Orders Config Statistics
      description: 'Statistics for a specific order config for the given time frame.


        Contains the following information:

        - Cumulative counts:

        - Order revenue

        - Order shipping costs

        - Amount spent on commission to marketplaces

        - Daily counts:

        - Order revenue

        - Order shipping costs

        - Amount spent on commission to marketplaces

        - Number of orders

        - Number of ordered products'
      operationId: single_orders_config_statistics_companies__company_id__projects__project_id__statistics_orders__order_config_id__get
      parameters:
      - name: order_config_id
        in: path
        required: true
        schema:
          type: integer
          title: Order Config Id
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
          title: Project Id
      - name: start_date
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: Start Date
      - name: end_date
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: string
            format: date-time
          - type: 'null'
          title: End Date
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderConfigStatistics'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    OrderStatistic:
      properties:
        id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Id
        label:
          anyOf:
          - type: string
          - type: 'null'
          title: Label
        points:
          $ref: '#/components/schemas/OrderStatisticPointList'
          title: Daily Revenue
        total_commission:
          type: string
          pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
          title: Total Commission
        total_orders:
          type: integer
          title: Total Orders
        total_products:
          type: integer
          title: Total Products
        total_revenue:
          type: string
          pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
          title: Total Revenue
        total_shipping:
          type: string
          pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
          title: Total Shipping
        currency:
          anyOf:
          - type: string
          - type: 'null'
          title: Currency
      type: object
      required:
      - points
      - total_commission
      - total_orders
      - total_products
      - total_revenue
      - total_shipping
      title: OrderStatistic
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OrderConfigStatistics:
      properties:
        name:
          type: string
          title: Name
        stats_total:
          items:
            $ref: '#/components/schemas/StatsPlot'
          type: array
          title: Cumulative Statistics
          description: Three point lists containing cumulative revenue, cumulative shipping costs and cumulative commission costs.
        stats_revenue:
          items:
            $ref: '#/components/schemas/StatsPlot'
          type: array
          title: Daily Statistics
          description: Three point lists containing daily revenue, daily shipping costs and daily commission costs.
        stats_orders:
          items:
            $ref: '#/components/schemas/StatsPlot'
          type: array
          title: Daily Statistics
          description: Two point lists containing daily order and ordered products counts.
      type: object
      required:
      - name
      - stats_total
      - stats_revenue
      - stats_orders
      title: OrderConfigStatistics
    OrderStatisticsTotals:
      properties:
        revenue:
          type: string
          pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
          title: Revenue
        commission:
          type: string
          pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
          title: Commission
        shipping:
          type: string
          pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
          title: Shipping
        orders:
          type: integer
          title: Orders
        products:
          type: integer
          title: Products
        currency:
          type: string
          title: Currency
      type: object
      required:
      - revenue
      - commission
      - shipping
      - orders
      - products
      - currency
      title: OrderStatisticsTotals
    OrderStatistics:
      items:
        $ref: '#/components/schemas/OrderStatistic'
      type: array
      title: OrderStatistics
    StatsPlot:
      properties:
        points:
          $ref: '#/components/schemas/OrderStatisticPointList'
          title: Plot Point
          description: Date and value for a single statistics point.
        label:
          type: string
          title: Label
        currency:
          anyOf:
          - type: string
          - type: 'null'
          title: Currency
      type: object
      required:
      - points
      - label
      title: StatsPlot
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    StatPoint:
      items:
        anyOf:
        - type: string
        - type: string
          pattern: ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
      type: array
      title: StatPoint
    OrderStatisticPointList:
      items:
        $ref: '#/components/schemas/StatPoint'
      type: array
      title: OrderStatisticPointList
    OrderStatisticsCombined:
      properties:
        order_statistics:
          $ref: '#/components/schemas/OrderStatistics'
          title: Single Orders Config Statistics
        total:
          anyOf:
          - $ref: '#/components/schemas/OrderStatisticsTotals'
          - type: 'null'
          title: Aggregate Orders Configs Statistics
      type: object
      required:
      - order_statistics
      - total
      title: OrderStatisticsCombined
